plugin:
  name: custom-data-type-gvk
  version: 1.0
  url: https://github.com/programmfabrik/easydb-custom-data-type-gvk
  displayname:
    de-DE: GVK-Verknüpfung
    en-US: GVK-Referencing
  info:
    de-DE: Stellt Verknüpfungen mit dem Gemeinsamen Verbundkatalog (GVK).
    en-US: Use for references to entities of the Gemeinsamen Verbundkatalog (GVK).
  server:
    api-version:
      require: 1
  webfrontend:
    url: custom-data-type-gvk.js
    l10n: l10n/
    css: custom-data-type-gvk.css
custom_types:
  gvk:
    mapping:
      conceptName:
        type: text
      conceptURI:
        type: text
    config:
      mask:
        - name: useCustomDatabases
          parameters:
            value:
              type: text
