plugin:
  name: custom-data-type-gvk
  version: 1.0
  url: https://github.com/programmfabrik/easydb-custom-data-type-gvk
  displayname:
    de-DE: GVK-Verknüpfung
    en-US: GVK-Referencing
  info:
    de-DE: Stellt Verknüpfungen mit dem Gemeinsamen Verbundkatalog (GVK).
    en-US: Use for references to entities of the Gemeinsamen Verbundkatalog (GVK).
  server:
    api-version:
      require: 1
  webfrontend:
    url: custom-data-type-gvk.js
    l10n: l10n/
custom_types:
  gvk:
    elasticsearch:
      mapping:
        type: object
        properties:
          conceptName:
            type: text
            index: no
            fields:
              exact:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: ez_exact_analyzer
              folded:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: ez_text_folded_analyzer
              fulltext:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: ez_text_fulltext_index_analyzer
                search_analyzer: ez_text_fulltext_search_analyzer
              phrase:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: ez_text_phrase_index_analyzer
                search_analyzer: ez_text_fulltext_search_analyzer
              sort:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: sort_de-DE
              suggest:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: ez_text_suggest_analyzer
              token:
                type: text
                term_vector: with_positions_offsets
                analyzer: ez_text_token_analyzer
          conceptURI:
            type: text
            index: no
            fields:
              exact:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: ez_exact_analyzer
              folded:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: ez_text_folded_analyzer
              fulltext:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: ez_text_fulltext_index_analyzer
                search_analyzer: ez_text_fulltext_search_analyzer
              phrase:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: ez_text_phrase_index_analyzer
                search_analyzer: ez_text_fulltext_search_analyzer
              sort:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: sort_de-DE
              suggest:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: ez_text_suggest_analyzer
              token:
                type: text
                fielddata: true
                term_vector: with_positions_offsets
                analyzer: ez_text_token_analyzer
