plugin:
  name: custom-data-type-gvk
  version: 2.0
  url: https://github.com/programmfabrik/easydb-custom-data-type-gvk
  displayname:
    de-DE: k10plus-Verknüpfung
    en-US: k10plus-Referencing
  info:
    de-DE: Stellt Verknüpfungen mit dem k10plus-Verbundkatalog her.
    en-US: Use for references to entities of the k10plus-Verbundkatalog her.
  server:
    api-version:
      require: 1
  webfrontend:
    url: custom-data-type-gvk.js
    l10n: l10n/
    css: custom-data-type-gvk.css
custom_types:
  gvk:
    update:
      script: build/updater/gvk-update.js
      timeout: 60
      batch_size: 100
      interval_base_config: update_interval_gvk.days
    mapping:
      conceptName:
        type: text
      conceptURI:
        type: text
    config:
      mask:
        - name: useCustomDatabases
          parameters:
            value:
              type: text
base_config:
  - name: update_interval_gvk
    group: update_custom_data_type
    parameters:
      days:
        type: int
        min: 0
        default: 0
        position: 0
